import React from "react";
import type { Metadata } from "next";

import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      <main className="flex flex-col lg:w-[960px] xl:w-[1024px] mx-auto mt-32 px-[24px] lg:px-0">
        {children}
      </main>
    </>
  );
}
